CREATE TABLE IF NOT EXISTS ROOM_RESERVATION (
id INT NOT NULL AUTO_INCREMENT,
 ROOM_TYPE VARCHAR(255), 
 TOTAL_ROOM_NUMBERs INT, 
 ROOM_BOOKING_START_DATE VARCHAR(255),
 ROOM_BOOKING_END_DATE VARCHAR(255),
 ROOM_AVAILABLE BOOLEAN, 
 PRICE_ROOM INT, 
 PRIMARY KEY (id));


